######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 25 00:08:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
