######################################################################
# Automatically generated by qmake (2.01a) Sun May 27 13:27:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
