######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 2 16:45:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
